### PR TITLE
Move signatures.db to mythril module

### LINKED ISSUE #823: Docker fails to run, produces stack trace
## Description

The current build on docker fails to run and produces a stack trace

## How to Reproduce

Run the following with any target solidity file

```
docker run --rm -v $(pwd):/tmp mythril/myth -x /tmp/target.sol
```

Observe the stack trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/myth", line 11, in <module>
    load_entry_point('mythril==0.19.10', 'console_scripts', 'myth')()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.10-py3.6.egg/mythril/interfaces/cli.py", line 293, in main
    enable_online_lookup=args.query_signature,
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.10-py3.6.egg/mythril/mythril.py", line 97, in __init__
    self.mythril_dir = self._init_mythril_dir()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.10-py3.6.egg/mythril/mythril.py", line 130, in _init_mythril_dir
    copyfile(str(parent_dir / "signatures.db"), db_path)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/mythril-0.19.10-py3.6.egg/signatures.db'
```

The following target.sol was used in this example:

https://gist.github.com/mickayz/4d58ed15edc60d301a4f60fe193e1212

## Expected behavior

No crash

## Environment

Latest Docker image running 0.19.10

### PR DESCRIPTION
**Pull request by norhh**
fixes #823 ,
It seems pypi and docker just installs the mythril module and not the entire home directory.

### CODE REVIEW

**Comment by xmxtc** [comment]
The problem still on for pypi install. How can I fix it manual?

**Comment by xmxtc** [comment]
> The problem still on for pypi install. How can I fix it manual?

I checkout the develop branch and use setup.py install the mythril. It still give me a mistake:

Traceback (most recent call last):
  File "/usr/local/bin/myth", line 11, in <module>
    load_entry_point('mythril==0.19.11', 'console_scripts', 'myth')()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/interfaces/cli.py", line 316, in main
    enable_online_lookup=args.query_signature,
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/mythril.py", line 109, in __init__
    enable_online_lookup=self.enable_online_lookup
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/support/signatures.py", line 38, in inner_wrapper
    return f(*args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/support/signatures.py", line 62, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/support/signatures.py", line 140, in __init__
    "CREATE TABLE IF NOT EXISTS signatures"
sqlite3.DatabaseError: file is not a database

**Comment by Ooqu4** [comment]
@Sekin: You need to download the __raw__ file like this:

```console
wget https://github.com/ConsenSys/mythril-classic/raw/develop/mythril/support/assets/signatures.db
```
Otherwise, you will only download the Github HTML file.

**Comment by Sekin** [comment]
@Ooqu4 You are right. I totally ignored that. @norhh Everything works fine with the download.

**Comment by Sekin** [comment]
@norhh I just took a look at the "new" version of [mythril.py](https://github.com/ConsenSys/mythril-classic/blob/develop/mythril/mythril.py) line 133:

```
db_path = str(Path(mythril_dir) / "signatures.db")
        if not os.path.exists(db_path):
            # if the default mythril dir doesn't contain a signature DB
            # initialize it with the default one from the project root
            asset_dir = Path(__file__).parent / "support" / "assets"
            copyfile(str(asset_dir / "signatures.db"), db_path)
```

In the version, pip3 is installing, this part still looks like this:

```
db_path = str(Path(mythril_dir) / "signatures.db")
        if not os.path.exists(db_path):
            # if the default mythril dir doesn't contain a signature DB
            # initialize it with the default one from the project root
            parent_dir = Path(__file__).parent
            copyfile(str(parent_dir / "signatures.db"), db_path)
```

The pip3 version just does not download the signatures.db into the `/path-to-your-python3-environment/lib/python3.x/site-packages/mythril/` directory. So, with a fresh install of `mythril` with `pip3`, it would be better to download the `signature.db` file into this directory so as not to have any errors.

Downloading it into `~/.mythril/` presupposes a prior execution of `myth` with the above error of `No such file or directory: '/home/sekin/ethereum-environment-3/lib/python3.6/site-packages/mythril/signatures.db'`, as this would be necessary to create the `~/.mythril/` directory. (Other than just creating it yourself.)

**Comment by norhh** [comment]
@Sekin Yes ,A new release will happen quite soon which won't have this bug.

**Pull request merged**
