### PR TITLE
Fix #576: Add a new CLI option to load contract creation bytecode from the command line

### LINKED ISSUE #576: Pass creation bytecode to mythril
Currently laser does model the creation of a contract, when dealing with SolidityContracts.
When using the command line option -c, mythril will still consider this to be runtime bytecode. An option needs to be added to support creation bytecode

### Requirements
 - Add cli option for creation bytecode
 - Adapt current cli "help" strings to this change
 - Change the analyis.symbolic so that the bytecode will be interpreted as creation bytecode

### PR DESCRIPTION
**Pull request by maxme**
Fix #576: Add a new CLI option to load contract creation bytecode from the command line

### CODE REVIEW

**Comment by norhh** [comment]
Hi @maxme, thanks for the pr, can you try fixing the tests

**Comment by maxme** [comment]
Tests run fine locally, circleci seems to be failing.

**Comment by maxme** [comment]
Tests run fine locally, circleci seems to be failing.

**Comment by maxme** [comment]
Tests run fine locally, circleci seems to be failing.

**Comment by maxme** [comment]
Tests run fine locally, circleci seems to be failing.

**Comment by JoranHonig** [comment]
@b-mueller We want creation bytecode to be the default right?

**Comment by maxme** [comment]
Do you want me to change this and replace the `--contract-creation` option by a `--bin-runtime` option (same name as the one used by `solc`)?

**Comment by JoranHonig** [comment]
I like that :+1:

**Comment by b-mueller** [comment]
Why idea why the 1 test is failing here?

**Comment by maxme** [comment]
>     * Why did you change signatures.json?

Sorry about that, I didn't notice it was modified and I committed it by mistake. I amended the commit at fault.

**Comment by JoranHonig** [comment]
@maxme Thanks for the contribution!

**Pull request merged**
