### PR TITLE
Configure call to webhook in Circle CI build

### PR DESCRIPTION
**Pull request by s0b0lev**
This variables should be added into Circle CI ENV variables:
```
ORGANIZATION 
WEBHOOK_PROJECT
CIRCLE_TOKEN
```

### CODE REVIEW

**Comment by norhh** [comment]
@s0b0lev , can you mention the exact variable values that are to be added?

**Comment by norhh** [comment]
@s0b0lev , any updates?

**Comment by s0b0lev** [comment]
@norhh I am still looking for a reason why environment variables are not injected into build. Also, I didn't find any other variables which was declared in Circle CI build env as well.

**Comment by s0b0lev** [comment]
@norhh , thanks to @fgimenez , issue is within settings, which is not allowed to inject env variables on forks. So I should use mythril-classic branch, and it should work. I will close this PR and create another one.

**Pull request closed without merging**
